name: Build Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
      - name: Install dependencies
        run: pdm install

      - name: Run build
        run: |
          BASE_URL=${{ steps.deployment.outputs.page_url }} pdm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: "./output"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
