name: Generate PDF Resume

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'typst_template.typ'
      - 'renderer/typst_generator.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-pdf:
    runs-on: macos-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        

      - name: Generate pdf files
        run: |
          pdm run pdf

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet resume_*.pdf || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push PDF files
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume_zh.pdf resume_en.pdf resume_zh.typ resume_en.typ
          git commit -m "chore: auto-generate PDF resumes [skip ci]"
          git push
